import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import AdBar from "@/components/AdBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b">
          <div className="mx-auto max-w-5xl p-4 flex items-center justify-between">
            <Link href="/" className="font-semibold">EverBloom</Link>
            <nav className="space-x-4 text-sm">
              <Link href="/games" className="hover:underline">Games</Link>
              <Link href="/calendar" className="hover:underline">Calendar</Link>
              <Link href="/diary" className="hover:underline">Diary</Link>
              <Link href="/video" className="hover:underline">Video</Link>
              <Link href="/couple" className="hover:underline">Couple</Link>
              <Link href="/pricing" className="hover:underline">Pricing</Link>
              <Link href="/surprises" className="hover:underline">Surprises</Link>
              <Link href="/login" className="hover:underline">Login</Link>
            </nav>
          </div>
        </header>
        <AdBar />
        <main className="mx-auto max-w-5xl p-4">{children}</main>
      </body>
    </html>
  );
}
